In [1]:
import pandas as pd

In [2]:
# Load the Online Retail II dataset into a Pandas DataFrame for data analysis
df = pd.read_excel(r'C:\Protfolio_Project\Project_9\online_retail_II.xlsx')

# Explor Data

In [3]:
# Inspect the dataset structure, including the number of rows, columns, data types, and column names
df.shape

(525461, 8)

In [4]:
df.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='str')

In [5]:
df.dtypes

Invoice                object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[us]
Price                 float64
Customer ID           float64
Country                   str
dtype: object

In [6]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      2928
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107927
Country             0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(6865)

In [8]:
df[df["Quantity"] <= 0]["Quantity"].count()

np.int64(12326)

In [9]:
df[df["Price"] <= 0]["Price"].count()

np.int64(3690)

In [10]:
df[df["Invoice"].astype(str).str.startswith("C")]["Invoice"].count()

np.int64(10206)

In [11]:
df["Country"].unique()

<ArrowStringArray>
[      'United Kingdom',               'France',                  'USA',
              'Belgium',            'Australia',                 'EIRE',
              'Germany',             'Portugal',                'Japan',
              'Denmark',              'Nigeria',          'Netherlands',
               'Poland',                'Spain',      'Channel Islands',
                'Italy',               'Cyprus',               'Greece',
               'Norway',              'Austria',               'Sweden',
 'United Arab Emirates',              'Finland',          'Switzerland',
          'Unspecified',                'Malta',              'Bahrain',
                  'RSA',              'Bermuda',            'Hong Kong',
            'Singapore',             'Thailand',               'Israel',
            'Lithuania',          'West Indies',              'Lebanon',
                'Korea',               'Brazil',               'Canada',
              'Iceland']
Length: 40, dtype: str

In [12]:
df["InvoiceDate"].min(), df["InvoiceDate"].max()

(Timestamp('2009-12-01 07:45:00'), Timestamp('2010-12-09 20:01:00'))

In [13]:
df[
    (df["Quantity"] <= 0)
    & (df["Invoice"].astype(str).str.startswith("C"))
].shape[0]

10205

In [14]:
df[
    (df['Quantity'] <= 0)
    & (~df['Invoice'].astype(str).str.startswith("C"))
].shape[0]

2121

In [15]:
df[
    (df['Quantity'] <= 0)
    & (~df['Invoice'].astype(str).str.startswith("C"))
][["Invoice", "StockCode", "Description", "Quantity", "Price", "Customer ID"]].head(20)

      Invoice StockCode      Description  Quantity  Price  Customer ID
263    489464     21733     85123a mixed       -96    0.0          NaN
283    489463     71477            short      -240    0.0          NaN
284    489467    85123A      21733 mixed      -192    0.0          NaN
470    489521     21646              NaN       -50    0.0          NaN
3114   489655     20683              NaN       -44    0.0          NaN
3162   489660     35956             lost     -1043    0.0          NaN
3168   489663    35605A          damages      -117    0.0          NaN
4296   489806     18010              NaN      -770    0.0          NaN
4538   489820     21133  invcd as 84879?      -720    0.0          NaN
4566   489821    85049G              NaN      -240    0.0          NaN
6556   489899   79323GR     sold as gold      -954    0.0          NaN
6576   489901     21098              NaN      -200    0.0          NaN
6911   490007     84347            21494      -720    0.0          NaN
7205   490016     21982              NaN     -1012    0.0          NaN
7559   490055     20620              NaN       -25    0.0          NaN
8553   490084     85064              NaN       -89    0.0          NaN
9308   490130     21493            lost?      -600    0.0          NaN
9667   490146     21558              NaN      -169    0.0          NaN
10508  490165     21493              NaN      -106    0.0          NaN
11973  490354     21489              NaN       -23    0.0          NaN

In [16]:
df[
    (df["Quantity"] <= 0) &
    (~df["Invoice"].astype(str).str.startswith("C"))
]["Price"].value_counts().head(10)

Price
0.0    2121
Name: count, dtype: int64

In [17]:
df[
    (df["Quantity"] <= 0) &
    (~df["Invoice"].astype(str).str.startswith("C"))
]['Description'].isna().sum()

np.int64(1827)

In [18]:
df[
    (df["Quantity"] <= 0) &
    (~df["Invoice"].astype(str).str.startswith("C"))
]["Description"].notna().sum()

np.int64(294)

In [19]:
df[
    (df['Quantity'] <= 0)
    & (~df['Invoice'].astype(str).str.startswith("C"))
    & (df['Description'].notna())
]['Description'].value_counts().head()

Description
?          42
damages    39
damaged    36
missing    24
dotcom      6
Name: count, dtype: int64

In [20]:
df[
    (df['Quantity'] <= 0)
    & (df['Price'] > 0)
].shape[0]

10205

In [21]:
df[
    (df['Price'] <= 0)
    & (df['Quantity'] > 0)
].shape[0]

1569

In [22]:
df[
    (df['Price'] <= 0)
    & (df['Quantity'] > 0)
]['Description'].value_counts().head(20)

Description
OWL DOORSTOP                           8
POLYESTER FILLER PAD 45x45cm           7
PICNIC BASKET WICKER LARGE             7
FLAG OF ST GEORGE CAR FLAG             6
HEART OF WICKER SMALL                  6
AIRLINE BAG VINTAGE WORLD CHAMPION     6
POLYESTER FILLER PAD 40x40cm           5
SMALL POPCORN HOLDER                   5
WATERING CAN BLUE ELEPHANT             5
ENAMEL FIRE BUCKET CREAM               5
ENAMEL WASH BOWL CREAM                 5
PICNIC BASKET WICKER SMALL             5
IVORY KITCHEN SCALES                   5
DOOR MAT UNION JACK GUNS AND ROSES     4
temp                                   4
MILK PAN PINK RETROSPOT                4
RED RETROSPOT STORAGE JAR              4
HANGING METAL STAR LANTERN             4
AIRLINE BAG VINTAGE TOKYO 78           4
WATERING CAN PINK BUNNY                4
Name: count, dtype: int64

In [23]:
df[
    (df["Price"] <= 0) &
    (df["Quantity"] > 0)
]["Price"].value_counts().sort_index()

Price
-53594.36       1
-44031.79       1
-38925.87       1
 0.00        1566
Name: count, dtype: int64

In [24]:
df[
    (df['Price'] < 0)
    & (df['Quantity'] > 0)
]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
179403,A506401,B,Adjust bad debt,1,2010-04-29 13:36:00,-53594.36,NaN,United Kingdom
276274,A516228,B,Adjust bad debt,1,2010-07-19 11:24:00,-44031.79,NaN,United Kingdom
403472,A528059,B,Adjust bad debt,1,2010-10-20 12:04:00,-38925.87,NaN,United Kingdom

In [25]:
df[df.duplicated(keep=False)]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
362,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
363,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
365,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
367,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
368,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
...,...,...,...,...,...,...,...,...
525170,538155,21907,I'M ON HOLIDAY METAL SIGN,1,2010-12-09 16:52:00,2.10,16907.0,United Kingdom
525292,538166,21915,RED HARMONICA IN BOX,5,2010-12-09 18:09:00,1.25,17965.0,United Kingdom
525293,538166,21915,RED HARMONICA IN BOX,5,2010-12-09 18:09:00,1.25,17965.0,United Kingdom
525330,538168,22739,RIBBON REEL CHRISTMAS SOCK BAUBLE,5,2010-12-09 19:23:00,1.65,14702.0,United Kingdom
525340,538168,22739,RIBBON REEL CHRISTMAS SOCK BAUBLE,5,2010-12-09 19:23:00,1.65,14702.0,United Kingdom

In [26]:
df.groupby('StockCode')['Description'].nunique().value_counts(ascending=False).head(20)

Description
1    3589
2     600
0     356
3      70
4      15
6       1
5       1
Name: count, dtype: int64

In [27]:
code = df.groupby('StockCode')['Description'].nunique().idxmax()

df[df['StockCode'] == code]['Description'].unique()

array(['REGENCY CAKESTAND 3 TIER', 'smashed', 'damaged', nan,
       'broken, uneven bottom', 'wonky bottom/broken', 'faulty'],
      dtype=object)

In [28]:
duplicates = df[df.duplicated(keep=False)]
duplicates['Invoice'].nunique()

2538

In [29]:
duplicates["Invoice"].value_counts().head(20)

Invoice
530437    58
525075    56
531922    48
537781    47
531382    43
533381    40
529156    38
533301    38
500356    37
512285    36
533841    36
531782    34
532821    34
501922    33
518227    33
509422    32
530796    32
530811    32
536796    31
497909    30
Name: count, dtype: int64

In [30]:
duplicates["Invoice"].value_counts().describe()

count    2538.000000
mean        5.233649
std         5.378480
min         2.000000
25%         2.000000
50%         4.000000
75%         6.000000
max        58.000000
Name: count, dtype: float64

In [31]:
duplicates.groupby(["Invoice", "StockCode"]).size().sort_values(ascending=False).head(20)

Invoice  StockCode
502660   17021        8
496431   84826        6
525065   20894        6
533841   22906        6
534219   35953        6
520570   21754        5
         21755        5
501425   85040B       5
492784   22114        5
530437   22585        5
530953   21231        5
537224   70007        5
532679   22264        5
536412   21448        5
501880   22055        4
502235   22467        4
494915   82587        4
491425   21817        4
491186   85081        4
497921   22072        4
dtype: int64

In [32]:
df[
    (df["Invoice"] == "502660") &
    (df["StockCode"] == "17021")
]

Empty DataFrame
Columns: [Invoice, StockCode, Description, Quantity, InvoiceDate, Price, Customer ID, Country]
Index: []

In [33]:
df[df["Invoice"].astype(str).str.contains("502660", na=False)]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
138577,502660,17021,NAMASTE SWAGAT INCENSE,18,2010-03-25 17:18:00,0.30,13187.0,United Kingdom
138578,502660,17033,"BROCADE PURSE,SMALL ARCH BUTTON",12,2010-03-25 17:18:00,0.29,13187.0,United Kingdom
138579,502660,75149N,STRING CRYSTALS NATURAL,6,2010-03-25 17:18:00,1.25,13187.0,United Kingdom
138580,502660,72598,SET/12 TAPER CANDLES,24,2010-03-25 17:18:00,0.85,13187.0,United Kingdom
138581,502660,17021,NAMASTE SWAGAT INCENSE,18,2010-03-25 17:18:00,0.30,13187.0,United Kingdom
138582,502660,17021,NAMASTE SWAGAT INCENSE,6,2010-03-25 17:18:00,0.30,13187.0,United Kingdom
138583,502660,17021,NAMASTE SWAGAT INCENSE,6,2010-03-25 17:18:00,0.30,13187.0,United Kingdom
138584,502660,17021,NAMASTE SWAGAT INCENSE,6,2010-03-25 17:18:00,0.30,13187.0,United Kingdom
138585,502660,17021,NAMASTE SWAGAT INCENSE,6,2010-03-25 17:18:00,0.30,13187.0,United Kingdom
138586,502660,17021,NAMASTE SWAGAT INCENSE,6,2010-03-25 17:18:00,0.30,13187.0,United Kingdom
138587,502660,17021,NAMASTE SWAGAT INCENSE,6,2010-03-25 17:18:00,0.30,13187.0,United Kingdom
138588,502660,17021,NAMASTE SWAGAT INCENSE,12,2010-03-25 17:18:00,0.30,13187.0,United Kingdom
138589,502660,17039,INLAID WOOD INCENSE HOLDER,9,2010-03-25 17:18:00,0.29,13187.0,United Kingdom
138590,502660,17084P,DRAGONS BLOOD INCENSE,25,2010-03-25 17:18:00,0.21,13187.0,United Kingdom
138591,502660,71477,COLOUR GLASS. STAR T-LIGHT HOLDER,3,2010-03-25 17:18:00,3.25,13187.0,United Kingdom
138592,502660,17084P,DRAGONS BLOOD INCENSE,25,2010-03-25 17:18:00,0.21,13187.0,United Kingdom
138593,502660,17084N,FAIRY DREAMS INCENSE,25,2010-03-25 17:18:00,0.21,13187.0,United Kingdom
138594,502660,21167,WHITE SAGE INCENSE,25,2010-03-25 17:18:00,0.21,13187.0,United Kingdom
138595,502660,M,Manual,6,2010-03-25 17:18:00,1.00,13187.0,United Kingdom
138596,502660,79329,PINK FLOCK GLASS CANDLEHOLDER,2,2010-03-25 17:18:00,1.65,13187.0,United Kingdom
138597,502660,M,Manual,7,2010-03-25 17:18:00,1.00,13187.0,United Kingdom
138598,502660,M,Manual,6,2010-03-25 17:18:00,1.00,13187.0,United Kingdom

In [34]:
df[
    df["Invoice"].astype(str).str.contains("502660", na=False)
][["Invoice", "StockCode", "Description", "Quantity", "InvoiceDate", "Price", "Customer ID"]]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID
138577,502660,17021,NAMASTE SWAGAT INCENSE,18,2010-03-25 17:18:00,0.30,13187.0
138578,502660,17033,"BROCADE PURSE,SMALL ARCH BUTTON",12,2010-03-25 17:18:00,0.29,13187.0
138579,502660,75149N,STRING CRYSTALS NATURAL,6,2010-03-25 17:18:00,1.25,13187.0
138580,502660,72598,SET/12 TAPER CANDLES,24,2010-03-25 17:18:00,0.85,13187.0
138581,502660,17021,NAMASTE SWAGAT INCENSE,18,2010-03-25 17:18:00,0.30,13187.0
138582,502660,17021,NAMASTE SWAGAT INCENSE,6,2010-03-25 17:18:00,0.30,13187.0
138583,502660,17021,NAMASTE SWAGAT INCENSE,6,2010-03-25 17:18:00,0.30,13187.0
138584,502660,17021,NAMASTE SWAGAT INCENSE,6,2010-03-25 17:18:00,0.30,13187.0
138585,502660,17021,NAMASTE SWAGAT INCENSE,6,2010-03-25 17:18:00,0.30,13187.0
138586,502660,17021,NAMASTE SWAGAT INCENSE,6,2010-03-25 17:18:00,0.30,13187.0
138587,502660,17021,NAMASTE SWAGAT INCENSE,6,2010-03-25 17:18:00,0.30,13187.0
138588,502660,17021,NAMASTE SWAGAT INCENSE,12,2010-03-25 17:18:00,0.30,13187.0
138589,502660,17039,INLAID WOOD INCENSE HOLDER,9,2010-03-25 17:18:00,0.29,13187.0
138590,502660,17084P,DRAGONS BLOOD INCENSE,25,2010-03-25 17:18:00,0.21,13187.0
138591,502660,71477,COLOUR GLASS. STAR T-LIGHT HOLDER,3,2010-03-25 17:18:00,3.25,13187.0
138592,502660,17084P,DRAGONS BLOOD INCENSE,25,2010-03-25 17:18:00,0.21,13187.0
138593,502660,17084N,FAIRY DREAMS INCENSE,25,2010-03-25 17:18:00,0.21,13187.0
138594,502660,21167,WHITE SAGE INCENSE,25,2010-03-25 17:18:00,0.21,13187.0
138595,502660,M,Manual,6,2010-03-25 17:18:00,1.00,13187.0
138596,502660,79329,PINK FLOCK GLASS CANDLEHOLDER,2,2010-03-25 17:18:00,1.65,13187.0
138597,502660,M,Manual,7,2010-03-25 17:18:00,1.00,13187.0
138598,502660,M,Manual,6,2010-03-25 17:18:00,1.00,13187.0

# Cleaning

In [35]:
# Create a copy of the original dataset so we keep the raw data unchanged

df_clean = df.copy()

In [36]:
# Remove exact duplicate rows to prevent the same transaction from being counted more than once
df_clean = df_clean.drop_duplicates()

In [37]:
# Check how many exact duplicate rows still exist after the cleaning step
df_clean.duplicated().sum()

np.int64(0)

In [38]:
# Calculate how many rows were removed during duplicate cleaning
rows_removed = len(df) - len(df_clean)

print('the number of removed rows', rows_removed)

the number of removed rows 6865

In [39]:
# Classify transactions with positive quantity and positive price as normal sales
df_clean.loc[
    (df_clean['Quantity'] > 0)
    & (df_clean['Price'] > 0),
    "Transaction_Type"
] = "Sales"

In [40]:
# Count how many transactions were classified as normal sales
df_clean['Transaction_Type'].value_counts(dropna = False)

Transaction_Type
Sales    504731
NaN       13865
Name: count, dtype: int64

In [41]:
# Classify transactions with non-positive quantity and positive price as return/cancellation candidates
df_clean.loc[
    (df_clean['Quantity'] <= 0)
    & (df_clean['Price'] > 0),
    "Transaction_Type"
] = "Return_Cancellation"

In [42]:
# Check the number of transactions in each transaction type after adding the return/cancellation classification
df_clean["Transaction_Type"].value_counts(dropna=False)

Transaction_Type
Sales                  504731
Return_Cancellation     10181
NaN                      3684
Name: count, dtype: int64

In [43]:
# Classify positive-quantity transactions with zero price as zero-price transactions
df_clean.loc[
    (df['Quantity'] > 0)
    & (df['Price'] == 0),
    "Transaction_Type"
] = "Zero_Price"

In [44]:
# Check the transaction type distribution after adding the zero-price classification
df_clean['Transaction_Type'].value_counts(dropna = False)

Transaction_Type
Sales                  504731
Return_Cancellation     10181
NaN                      2124
Zero_Price               1560
Name: count, dtype: int64

In [45]:
# Classify transactions with a negative price as financial adjustments
df_clean.loc[
    df_clean["Price"] < 0,
    "Transaction_Type"
] = "Financial_Adjustment"

In [46]:
# Check the final distribution of transaction types after adding the financial adjustment classification
df_clean["Transaction_Type"].value_counts(dropna=False)

Transaction_Type
Sales                   504731
Return_Cancellation      10181
NaN                       2121
Zero_Price                1560
Financial_Adjustment         3
Name: count, dtype: int64

In [47]:
# Mark transactions that do not match any confirmed business rule as unclassified
df_clean.loc[
    df_clean['Transaction_Type'].isna(),
    "Transaction_Type"
] = 'Unclassified'

In [48]:
# Check the final distribution of all transaction types
df_clean["Transaction_Type"].value_counts()

Transaction_Type
Sales                   504731
Return_Cancellation      10181
Unclassified              2121
Zero_Price                1560
Financial_Adjustment         3
Name: count, dtype: int64

# Final Validation

In [49]:
# Check the final number of rows and columns after the cleaning process
df_clean.shape

(518596, 9)

In [50]:
# Check the final distribution of transaction types to make sure all transactions are classified
df_clean["Transaction_Type"].value_counts()

Transaction_Type
Sales                   504731
Return_Cancellation      10181
Unclassified              2121
Zero_Price                1560
Financial_Adjustment         3
Name: count, dtype: int64

In [51]:
# Check whether any transactions are still missing a transaction type
df_clean["Transaction_Type"].isna().sum()

np.int64(0)

In [52]:
# Export the cleaned dataset to a CSV file so we can load it into SQL Server
df_clean.to_csv('online_retail_cleaned.csv', index = False)